[workspace]
resolver = "3"
members = [
    "cliva",
    "cliva-io",
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/theNexmentProject/cliva"
homepage = "https://app.nexment.in/projects/cliva"
readme = "README.md"
keywords = ["cli", "command-line", "terminal", "rust"]
categories = ["command-line-interface", "command-line-utilities"]

[workspace.dependencies]
cliva-io = { path = "cliva-io", version = "0.1.5" }
